apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: python:3.10-slim
        env:
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password
        command: ["sh", "-c", "echo Password is: $APP_PASSWORD && sleep 3600"]
