apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: my-flask-app

#minikube service my-flask-app-service --url
