apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30000
  selector:
    app: my-flask-app
