---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    password: AgC1nDt1ih43AX8uJSxm3MNKqEPanujFkHOtX+pRKgAsXLx8fyr3jiz1rwmThkEDkOoFSJPhpLivMgkqq8cDRzxcYgVhgWcRzIdo15+i9Y9AN/dZb7T6YvjrMJoyHpj+vxDJYYZaHUX3tHR0VcMXc+lEOwKGF6GF51Kwf9MMZ1GtMDYZdIarbJTTLx8B4ORglJuDB+RskvhKyKLeQhxgmXq+o8ooZr58RAF91b8ms3iKmern1ORCcyFvDZ8oekijhG/yXDdIZamG/Ny23Xl2lVCqU+xSOPFtC4y4gxhL8BlckOkaNiTiiJ+iHfxv8yNr7HLFbXFqrsfDy7vugxXXrNpt0zCUx/ExD7WxpL3y8K63Th4kAsVD02Rtok8sZdwNyfFHSGU6x2cQnnOamLxsrz/6fvxh57FSsTP/b7bH63S/bqnVHfqkXisQLJ4pRtHBgJOcA5/yAf2KwfiIY5e8H42SmgO/38uo7A+Lwi+SoZiQN8Yauxpoj6ofPm5DPiJdI+XEP+rHdlwOwP++crQMJ1tlZXHAifrbQG5oE03MaD6iqrHBd4Zq4niL74JaDSWbVf6qonNpVJUUmoxqoJxgmWKKxGm5EwLgayqH3kzCD81r4CgIYZLADYpEaE7UueegfonJ1uZDwwxq9ywZUyCVsJxrlcSuppgmzuIeXedl2ROxcCXbrXo8Yk8zWnhvlNfTAAUsIRDijMFw5A==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
    type: Opaque
